#!/usr/bin/env bash
# this script prints "Best School" 10 times, but for
# the 4th iteration, prints "bad luck" and
# "good luck" o the 8th iteration

i=1
while [ $i -le 10 ]
do
if [ $i -eq 4 ]
then
echo "bad luck"
elif [ $i -eq 8 ]
then
echo "good luck"
else
echo "Best School"
fi
i=$((i+1))
done
