#!/usr/bin/env bash
# diplays 1 to 10
# on 4th iteration, "bad luck from China"
# on 9th iteration, "bad luck from Japan"
# on 17th iteration, "bad luck from Italy"
# all in new line

i=1
while [ $i -le 20 ]
do
case $i in
4)
echo "$i"
echo "bad luck from China"
;;
9)
echo "$i"
echo "bad luck from Japan"
;;
17)
echo "$i"
echo "bad luck from Italy"
;;
*)
echo "$i"
;;
esac
i=$((i+1))
done
